version: '3'
services:
  mysql:
    build: ./mysql
    ports:
        - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=admin
    volumes:
        - ./db:/var/lib/mysql
  web:
    build: ./web
    hostname: virtualhost
    domainname: virtualhost.com
    ports:
          - 80:80 #local/virtual
    volumes:
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./apache2/sites-available:/etc/apache2/sites-available
      - ./apache2/log:/var/log/apache2
      - /var/www:/var/www
    restart: always
    environment:
           - DB_HOST=mysql:3306
    depends_on:
          - mysql