version: '3'
services:
  web:
    build: ./web
    hostname: virtualhost
    domainname: virtualhost.com
    ports:
          - 8000:80
    volumes:
      - /etc/apache2/sites-enabled:/etc/apache2/sites-enabled
      - /etc/apache2/sites-available:/etc/apache2/sites-available
      - /var/www:/var/www
    restart: always